<?php

namespace minipoBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{

    public function remove($id){
        $qb= $this->getEntityManager()->createQuery("Delete minipoBundle:Notification n where n.id like '".$id."%'")
            ->execute();
    }
}
